# Generated by Django 2.1.1 on 2018-10-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origiN', models.CharField(max_length=30)),
                ('destinatioN', models.CharField(max_length=30)),
                ('citY', models.CharField(max_length=30, null=True)),
                ('latitudE', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitudE', models.DecimalField(decimal_places=7, max_digits=9)),
                ('temperaturE', models.FloatField()),
                ('humiditY', models.FloatField()),
                ('pressurE', models.FloatField()),
                ('descriptioN', models.CharField(max_length=200)),
                ('icoN', models.CharField(max_length=10)),
            ],
        ),
    ]
